{% set name = "jxrlib" %}
{% set version = "None" %}
{% set sha256 = "a8d4633e18731bdeebbb56a055c9f636a288445df96df5773742d64ffc1a69be" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://http.debian.net/debian/pool/main/{{ name[0] }}/{{ name }}/{{ name }}_{{ version }}.orig.tar.gz
  sha256: {{ sha256 }}
  patches:
    - usecmake.patch  # [unix]

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('jxrlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [unix]
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libjxrglue${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/libjpegxr${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\libjxrglue.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\libjpegxr.lib exit 1  # [win]

about:
  home: https://packages.debian.org/source/sid/jxrlib
  license: BSD-2-Clause
  summary: "jxrlib - JPEG XR Library by Microsoft, built from Debian hosted sources."
  description: "This package seems to be no longer maintained by the original developer (Microsoft)."
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - csachs
    - hmaarrfk
