# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Yg+5R3Zw/AC4lW5n0QrAV7SlJ5BU9vyNysuhUFulj7URo32PjeFYLFaAKPi8Fy3Ug8bL+RXvfxuWvqDIB2XQWRnj5vmEXdaxsiUEQho1Gjri8IOzfuzGUoDwm8/mKm78L8IfwNSULeOjCHWFPqx/ioKezZV1ZNlq1wZCk36MICN+eu3HX6kPUDTyXdZ6rs5rtzKwKfoGWfRpGIXzDd3TP5gDK3cfGU5RUTkfDJSlxqdzvuo7baBM67d3PGwhFhus9nOjJkioS0HhTbAMzff1zV4es+KYWIH9zG1tJu7O4cNIKW4X2F0L/GF58Xd2Q+ZWjtlREXlcdYa+GDcJsNPgITSXd31Sm9J5zCCj9lyYbC9PEPJay/qSsVTxI9PJnLYUiAP1AJKboHsuIqwmeER7NM4RcVvLQ+oXMy9gpUjnpMPEGtBq1eT6ZiiJ1oihwxpz7ECSR0NWbH38vSGYqh+ooAFjQDjo1/lfzcPdC5r47Xv3Aar9qqZDRlSVh3kI00z0JkXU041wgykmLTU0UvNDEUuxcHJiCnI1pSYxTYd9XGwS2DZ8K2vuVy7Q7qa9oqp5cyf3uKSbXgQ1bE7rBYUaih2aR+2+/KDHj8bpESiuSlFEq5IRLLKqiwp2vdE3bH9Eo6fkGBkDUDf4NhqaSKF60QYWY47Oi896V+5OohuLbQY="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi